export const BAD_TOKEN = 'BAD_TOKEN';
export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const VALIDATION_FAILED = 'VALIDATION_FAILED';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
